"""empty message

Revision ID: 45205c48b129
Revises: d510381675a5
Create Date: 2021-11-01 16:05:07.636215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45205c48b129'
down_revision = 'd510381675a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_phone_number', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_phone_number', 'users', ['phone_number'])
    # ### end Alembic commands ###
